<?php
/**
* @file
* Contact info module that provides blocks and tokens.
*/

/**
 * Implements hook_menu().
 */
function contact_info_menu() {
  $items['admin/content/contact-info'] = array(
    'title' => 'Contact information',
    'file' => 'includes/contact_info.admin.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('contact_info_setup'),
    'access arguments' => array('modify contact info'),
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function contact_info_permission() {
  return array(
    'modify contact info' =>  array(
      'title' => t('Modify contact information'),
      'description' => t('Modify contact and social media information.'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function contact_info_theme() {
  return array(
    'contact_info_social_media_draggable_table' => array(
      'render element' => 'form',
      'file' => 'includes/contact_info.admin.inc',
    ),
    'contact_info_address' => array(
      'variables' => array(
        'country_name' => NULL,
        'legal_name' => NULL,
        'street_address' => NULL,
        'locality' => NULL,
        'region' => NULL,
        'postal_code' => NULL,
        'phone' => NULL,
        'fax' => NULL,
      ),
      'template' => 'contact_info_address',
    ),
  );
}

/**
 * Processes variables twitter_pull templates.
 */
function contact_info_preprocess(&$variables, $hook) {
  switch ($hook) {
    case 'contact_info_address':
      // Any preprocessing should go here.
      break;
  }
}

/**
 * Implements hook_token_info().
 */
function contact_info_token_info() {
  $info = array();
  // Define new token type.
  $info['types']['contact_info'] = array(
    'name' => t('Contact info'),
    'description' => t('A token type that provides data from the contact info module.'),
  );
  // Define new tokens.
  $info['tokens']['contact_info']['contact_info_address'] = array(
    'name' => t('Address'),
    'description' => t('A token containing the address entered in the contact info form.'),
  );
  $info['tokens']['contact_info']['contact_info_phone'] = array(
    'name' => t('Phone'),
    'description' => t('A token containing the phone number entered in the contact info form.'),
  );

  return $info;
}

/**
 * Implements hook_tokens().
 */
function contact_info_tokens($type, $tokens, array $data = array(), array $options = array()) {
  // Grab contact info data
  $contact_info = variable_get('contact_info', '');

  $replacements = array();

  if ($type == 'contact_info') {
    // Loop through available tokens.
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'contact_info_address':
          $replacements[$original] = $contact_info['contact_address'];
          break;
        case 'contact_info_phone':
          $replacements[$original] = $contact_info['contact_phone']['number'];
      }
    }
  }

  return $replacements;
}

/**
 * Implements hook_contextual_links_view_alter().
 */
function contact_info_contextual_links_view_alter(&$element, &$items) {
  // Contextual link to edit contact info.
  if (isset($element['#element']['#block']) && $element['#element']['#block']->delta == 'contact_info_block') {
    $element['#links']['edit-content'] = array(
      'title' => 'Edit contact info',
      'href' => url('admin/content/contact-info', array(
        'absolute' => TRUE,
        'query' => array(
          'destination' => current_path(),
        ),
      )),
    );
  }
  // Contextual link to edit social media links.
  if (isset($element['#element']['#block']) && $element['#element']['#block']->delta == 'social_media_block') {
    $element['#links']['edit-content'] = array(
      'title' => 'Edit social media links',
      'href' => url('admin/content/contact-info', array(
        'absolute' => TRUE,
        'query' => array(
          'destination' => current_path(),
        ),
      )),
    );
  }
}

/**
 * Implements hook_block_info().
 */
function contact_info_block_info() {
  $blocks['contact_info_block'] = array(
    'info' => t('Contact info block'),
  );

  $blocks['social_media_block'] = array(
    'info' => t('Social media block'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function contact_info_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'contact_info_block':
      $block['content'] = contact_info_block_content();
      break;
    case 'social_media_block':
      $block['content'] = social_media_block_content();
      break;
  }

  return $block;
}

/**
 * Content for contact info block.
 */
function contact_info_block_content() {
  // Grab contact info data.
  $contact_info = variable_get('contact_info', '');
  
  // Set up variables to send to the theme function.
  $variables = array();
  
  // Phone.
  $phone = $contact_info['contact_phone'];
  if (isset($phone['number']) && $phone['number']) {
    if (!isset($phone['label']) || !strlen($phone['label'])) {
      $phone['label'] = 'Phone';
    }
    
    if (!isset($phone['country_code']) && !strlen($phone['country_code'])) {
      $phone['country_code'] = '1';
    }

    $phone['machine'] = preg_replace('/[^0-9]/', '', $contact_info['contact_phone']['number']);
    $variables['phone'] = check_plain($phone['label']) . ': ' .  
      l($phone['number'], 'tel:+' . $phone['country_code'] . $phone['machine'], array(
        'attributes' => array(
          'itemprop' => 'telephone',
          'class' => array('telephone'),
        ),
      ));
  }
  
  // Fax.
  $fax = $contact_info['contact_fax'];
  if (isset($fax['number']) && $fax['number']) {
    if (!isset($fax['label']) || !strlen($fax['label'])) {
      $fax['label'] = 'Fax';
    }

    $variables['fax'] = check_plain($fax['label']) . ': ' . 
      '<span itemprop="faxNumber">' . check_plain($fax['number']) . '</span>';
  }
  
  // Address.
  $mappings = array(
    'country-name' => 'country_name',
    'legalName' => 'legal_name',
    'street-address' => 'street_address',
    'locality' => 'locality',
    'region' => 'region',
    'postal-code' => 'postal_code',
  );
  foreach ($contact_info['contact_address'] as $key => $value) {
    if (isset($value) && strlen($value)) {
      $variables[$mappings[$key]] = check_plain($value);
    }
  }

  $output = theme('contact_info_address', $variables);
  return $output;
}

/**
 * Content for social media block.
 */
function social_media_block_content() {
  $data = array();

  $contact_info = variable_get('contact_info', '');

  // Structure data for output.
  foreach ($contact_info['social_media'] as $key => $social_media_site) {
    if ($social_media_site && $social_media_site['enable']) {
      $data[$key] = array(
        'url' => $social_media_site['url'],
        'weight' => $social_media_site['weight'],
        'key' => $social_media_site['key'],
      );
    }
  }

  // Sort data array by weight.
  uasort($data, 'contact_info_sort_weight');

  $output = array();

  // Build render array to output social media links.
  if ($data) {
    foreach ($data as $social_media_site_key => $social_media_site) {
      $output[$social_media_site_key] = array(
        '#theme' => 'link',
        '#text' => $social_media_site['key'],
        '#path' => $social_media_site['url'],
        '#options' => array(
          'attributes' => array(
            'class' => array(
              $social_media_site_key,
              'contact-info-social-icon',
            ),
            'target' => '_blank',
          ),
          'html' => TRUE,
        ),
      );
    }
  }

  return $output;
}

/**
 * Helper function to sort weights.
 */
function contact_info_sort_weight($a, $b) {
  if (isset($a['weight']) && isset($b['weight'])) {
    return ($a['weight'] - $b['weight']);
  }
}